---
title: "Small_Data_pull"
author: "Daniel Dominguez"
date: "2024-02-22"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(dataRetrieval)
library(data.table)
library(dplyr)
library(zoo)
```

```{r}
local_path<-"/Users/danieldominguez/Documents/Code/NASA_ILOH/"

getwd()
```


```{r}

# Define the HUC codes of interest
huc_codes <- c("07")
parameter_codes <- c("00060","00010","32316")
start_date <- "2021-05-01"
end_date <- "2024-01-01"

gauges<- whatNWISsites(huc="07",parameterCd="32316", 
                               startDate = start_date,
                               endDate = end_date)

sites<-gauges %>% 
  select(site_no) %>% 
  as.list()

```

```{r}
for (site in sites$site_no) {
  for (parameter_code in parameter_codes) {
    data <- readNWISdata(sites = site, parameterCd = parameter_code, 
                         startDate = start_date, endDate = end_date,
                         service="dv")
    filename <- paste("site_", site, "_parameter_", parameter_code, ".csv", sep = "")
    write.csv(data, file = file.path(local_path, "Data", filename),row.names = FALSE)
  }
}
```

```{r}
# Function to read CSV files with the same parameter code and combine them
# This only works for discharge because supergauges are using a weird naming convention in columns
# This in theory should work for other param codes that are not supergauge sites. 
read_csv_same_parameter_code <- function(directory, parameter_code) {
  # Get list of files matching the parameter code pattern in the directory
  files <- list.files(directory, pattern = paste0("^site_.*_parameter_", parameter_code, "\\.csv$"), full.names = TRUE)
  
  # Initialize an empty list to store dataframes
  data_list <- list()
  
  # Loop through each file
  for (file in files) {
    # Read the CSV file
    temp_data <- read.csv(file, stringsAsFactors = FALSE)
    
    # Check if the number of columns is greater than or equal to four
    if (ncol(temp_data) >= 4) {
      # Select specific columns
      selected_columns <- c(2, 3, 4, (ncol(temp_data) - 2):(ncol(temp_data) - 1), ncol(temp_data))
      temp_data <- temp_data[, selected_columns]
      
      # Rename the third to last and second to last columns
      names(temp_data)[ncol(temp_data) - 1] <- "code"
      names(temp_data)[ncol(temp_data) - 2] <- "value"
      
      # Append data to the list
      data_list <- append(data_list, list(temp_data))
    } else {
      # Skip the file and print a message
      cat("Skipping file", file, "as it has fewer than four columns.\n")
      next
    }
  }
  
  # Combine all dataframes into a single dataframe
  if (length(data_list) > 0) {
    combined_data <- do.call(rbind, data_list)
    
    # Return the combined dataframe
    return(combined_data)
  } else {
    # If no valid files were found, return NULL
    cat("No valid files found for parameter code", parameter_code, "\n")
    return(NULL)
  }
}


```

```{r}
# Example usage:
directory <- paste0(local_path,"Data/") # Replace with the directory path where your files are located

data_combined_00060 <- read_csv_same_parameter_code(directory, "00060") %>% 
  mutate(parameter="Q_cfs")



```

# Process supergaugues
```{r}
start_date <- "2021-04-16"
end_date <- "2024-03-20"

data_05536356_32316 <- readNWISdata(sites = "05536356", parameterCd = "32316",
                     startDate = start_date, endDate = end_date,
                     service="dv") 


# Initialize new column chl_a
data_05536356_32316$chl_a <- NA

# Loop over each row
for (i in 1:nrow(data_05536356_32316)) {
  # Check if X column is not NA, then assign its value to chl_a
  if (!is.na(data_05536356_32316$X_32316_00003[i])) {
    data_05536356_32316$chl_a[i] <- data_05536356_32316$X_32316_00003[i]
  } else {
    # If X is NA, check Y column
    if (!is.na(data_05536356_32316$X_AOC.EXO.15K103372_32316_00003[i])) {
      data_05536356_32316$chl_a[i] <- data_05536356_32316$X_AOC.EXO.15K103372_32316_00003[i]
    } else {
      data_05536356_32316$chl_a[i] <- NA
    }
  }
}

data_05536356_32316<-data_05536356_32316 %>% 
  select(site_no,dateTime,chl_a)

data_05536356_00010 <- readNWISdata(sites = "05536356", parameterCd = "00010",
                     startDate = start_date, endDate = end_date,
                     service="dv") 


# Initialize new column chl_a
data_05536356_00010$temp_C <- NA

# Loop over each row
for (i in 1:nrow(data_05536356_00010)) {
  # Check if X column is not NA, then assign its value to chl_a
  if (!is.na(data_05536356_00010$X_AOC.EXO.15K103372_00010_00003[i])) {
    data_05536356_00010$temp_C[i] <- data_05536356_00010$X_AOC.EXO.15K103372_00010_00003[i]
  } else {
    # If X is NA, check Y column
    if (!is.na(data_05536356_00010$X_.YSI._00010_00003[i])) {
      data_05536356_00010$temp_C[i] <- data_05536356_00010$X_.YSI._00010_00003[i]
    } else {
      # If Y is also NA, check Z column
      if (!is.na(data_05536356_00010$X_.SL._00010_00003[i])) {
        data_05536356_00010$temp_C[i] <- data_05536356_00010$X_.SL._00010_00003[i]
      } else {
        # If all are NA, assign NA to chl_a
        data_05536356_00010$temp_C[i] <- NA
      }
    }
  }
}

data_05536356_00010<-data_05536356_00010 %>% 
  select(site_no,dateTime,temp_C)

# data_05536356_00095 <- readNWISdata(sites = "05536356", parameterCd = "00095",
#                      startDate = start_date, endDate = end_date,
#                      service="dv") 
# 
# data_05536356_00095$spec_cond <- NA
# 
# # Loop over each row
# for (i in 1:nrow(data_05536356_00095)) {
#   # Check if X column is not NA, then assign its value to chl_a
#   if (!is.na(data_05536356_00095$X_AOC.EXO.15K103372_00095_00003[i])) {
#     data_05536356_00095$spec_cond[i] <- data_05536356_00095$X_AOC.EXO.15K103372_00095_00003[i]
#   } else {
#     # If X is NA, check Y column
#     if (!is.na(data_05536356_00095$X_00095_00003[i])) {
#       data_05536356_00095$spec_cond[i] <- data_05536356_00095$X_00095_00003[i]
#     }
#   }
# }
# 
# data_05536356_00095<-data_05536356_00095 %>% 
#   select(site_no,dateTime,spec_cond)

data_05536356_00300 <- readNWISdata(sites = "05536356", parameterCd = "00300",
                     startDate = start_date, endDate = end_date,
                     service="dv") 

data_05536356_00300$DO <- NA

# Loop over each row
for (i in 1:nrow(data_05536356_00300)) {
  # Check if X column is not NA, then assign its value to chl_a
  if (!is.na(data_05536356_00300$X_AOC.EXO.15K103372_00300_00003[i])) {
    data_05536356_00300$DO[i] <- data_05536356_00300$X_AOC.EXO.15K103372_00300_00003[i]
  } else {
    # If X is NA, check Y column
    if (!is.na(data_05536356_00300$X_SuperGage_00300_00003[i])) {
      data_05536356_00300$DO[i] <- data_05536356_00300$X_SuperGage_00300_00003[i]
    }
  }
}

data_05536356_00300<-data_05536356_00300 %>% 
  select(site_no,dateTime,DO)


data_05536356_00060<-readNWISdata(sites = "05536356", parameterCd = "00060",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  dplyr::select(site_no,dateTime, Q_cfs=X_00060_00003)
  

site_05536356_munged<-left_join(data_05536356_00060,data_05536356_32316, by=c("site_no","dateTime"))

site_05536356_munged<-left_join(site_05536356_munged,data_05536356_00300, by=c("site_no","dateTime"))

site_05536356_munged<-left_join(site_05536356_munged,data_05536356_00010, by=c("site_no","dateTime")) %>% 
  mutate(T_Q=temp_C/Q_cfs)

```

```{r}
start_date <- "2021-03-24"
end_date <- "2024-03-20"

data_05559900_32316 <- readNWISdata(sites = "05559900", parameterCd = "32316",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(site_no,dateTime, chl_a=X_32316_00003)


data_05559900_00010 <- readNWISdata(sites = "05559900", parameterCd = "00010",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime,temp_C=X_00010_00003)

# data_05559900_00095 <- readNWISdata(sites = "05559900", parameterCd = "00095",
#                      startDate = start_date, endDate = end_date,
#                      service="dv") %>% 
#   select(dateTime,spec_cond=X_00095_00003)

data_05559900_00300 <- readNWISdata(sites = "05559900", parameterCd = "00300",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime,DO=X_00300_00003)

# For now this is the nearest gauge in the river with discharge in the main stem of the Illinois
data_05559900_00060 <- readNWISdata(sites = "05568500", parameterCd = "00060",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime, Q_cfs=X_00060_00003)


site_05559900_munged<-left_join(data_05559900_32316, data_05559900_00060, by=c("dateTime"))

site_05559900_munged<-left_join(site_05559900_munged, data_05559900_00300, by=c("dateTime"))

site_05559900_munged<-left_join(site_05559900_munged,data_05559900_00010, by=c("dateTime")) %>% 
  mutate(T_Q=temp_C/Q_cfs)

```

```{r}
start_date <- "2021-04-16"
end_date <- "2024-03-20"

data_413646087260101_32316 <- readNWISdata(sites = "413646087260101", parameterCd = "32316",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(site_no,dateTime, chl_a=X_32316_00003)

data_413646087260101_00010 <- readNWISdata(sites = "413646087260101", parameterCd = "00010",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime,temp_C=X_00010_00003)

data_413646087260101_00300 <- readNWISdata(sites = "413646087260101", parameterCd = "00300",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime,DO=X_00300_00003)

data_413646087260101_00060<-readNWISdata(sites = "04092677", parameterCd = "00060",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  dplyr::select(dateTime, Q_cfs=X_00060_00003)
  


site_413646087260101_munged<-left_join(data_413646087260101_32316,data_413646087260101_00060, by=c("dateTime"))

site_413646087260101_munged<-left_join(site_413646087260101_munged,data_413646087260101_00300, by=c("dateTime"))

site_413646087260101_munged<-left_join(site_413646087260101_munged,data_413646087260101_00010, by=c("dateTime")) %>% 
  mutate(T_Q=temp_C/Q_cfs)
```

# Ohio basin
```{r}
start_date <- "2021-06-16"
end_date <- "2024-03-20"

data_03378500_32316 <- readNWISdata(sites = "03378500", parameterCd = "32316",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(site_no,dateTime, chl_a=X_32316_00003)

data_03378500_00010 <- readNWISdata(sites = "03378500", parameterCd = "00010",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime,temp_C=X_00010_00003)

data_03378500_00300 <- readNWISdata(sites = "03378500", parameterCd = "00300",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime,DO=X_00300_00003)

data_03378500_00060<-readNWISdata(sites = "03378500", parameterCd = "00060",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  dplyr::select(dateTime, Q_cfs=X_00060_00003)
  


site_03378500_munged<-left_join(data_03378500_32316,data_03378500_00060, by=c("dateTime"))

site_03378500_munged<-left_join(site_03378500_munged,data_03378500_00300, by=c("dateTime"))

site_03378500_munged<-left_join(site_03378500_munged,data_03378500_00010, by=c("dateTime")) %>% 
  mutate(T_Q=temp_C/Q_cfs)
```

```{r}
start_date <- "2021-06-16"
end_date <- "2024-03-20"

data_03303280_32316 <- readNWISdata(sites = "03303280", parameterCd = "32316",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(site_no,dateTime, chl_a=X_32316_00003)

data_03303280_00010 <- readNWISdata(sites = "03303280", parameterCd = "00010",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime,temp_C=X_00010_00003)

data_03303280_00300 <- readNWISdata(sites = "03303280", parameterCd = "00300",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime,DO=X_00300_00003)

data_03303280_00060<-readNWISdata(sites = "03303280", parameterCd = "00060",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  dplyr::select(dateTime, Q_cfs=X_00060_00003)
  


site_03303280_munged<-left_join(data_03303280_32316,data_03303280_00060, by=c("dateTime"))

site_03303280_munged<-left_join(site_03303280_munged,data_03303280_00300, by=c("dateTime"))

site_03303280_munged<-left_join(site_03303280_munged,data_03303280_00010, by=c("dateTime")) %>% 
  mutate(T_Q=temp_C/Q_cfs)
```

```{r}
start_date <- "2021-06-16"
end_date <- "2024-03-20"

data_03216070_32316 <- readNWISdata(sites = "03216070", parameterCd = "32316",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(site_no,dateTime, chl_a=X_32316_00003)

data_03216070_00010 <- readNWISdata(sites = "03216070", parameterCd = "00010",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime,temp_C=X_00010_00003)

data_03216070_00300 <- readNWISdata(sites = "03216070", parameterCd = "00300",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  select(dateTime,DO=X_00300_00003)

data_03216070_00060<-readNWISdata(sites = "03216070", parameterCd = "00060",
                     startDate = start_date, endDate = end_date,
                     service="dv") %>% 
  dplyr::select(dateTime, Q_cfs=X_00060_00003)
  


site_03216070_munged<-left_join(data_03216070_32316,data_03216070_00060, by=c("dateTime"))

site_03216070_munged<-left_join(site_03216070_munged,data_03216070_00300, by=c("dateTime"))

site_03216070_munged<-left_join(site_03216070_munged,data_03216070_00010, by=c("dateTime")) %>% 
  mutate(T_Q=temp_C/Q_cfs)
```


```{r}

# This is a lake wont use until I figure out how to do Q
# start_date <- "2021-04-15"
# end_date <- "2024-01-01"
# 
# data_423784088133401_32316 <- readNWISdata(sites = "423784088133401", parameterCd = "32316",
#                      startDate = start_date, endDate = end_date,
#                      service="dv") %>% 
#   select(site_no,dateTime, chl_a=X_32316_00003)
# 
# data_423784088133401_00010 <- readNWISdata(sites = "423784088133401", parameterCd = "00010",
#                      startDate = start_date, endDate = end_date,
#                      service="dv") %>% 
#   select(dateTime,temp_C=X_00010_00003)
# 
# data_423784088133401_00060<-readNWISdata(sites = "423784088133401", parameterCd = "00060",
#                      startDate = start_date, endDate = end_date,
#                      service="dv") %>% 
#   dplyr::select(dateTime, Q_cfs=X_00060_00003)
#   
# 
# site_423784088133401_munged<-left_join(data_423784088133401_32316,data_423784088133401_00060, by=c("dateTime"))
# 
# site_423784088133401_munged<-left_join(site_423784088133401_munged,data_423784088133401_00010, by=c("dateTime")) %>% 
#   mutate(T_Q=temp_C/Q_cfs)
```

```{r}
munged_data<-rbind(site_05536356_munged,site_05559900_munged,site_413646087260101_munged,
                   site_03378500_munged, site_03303280_munged,site_03216070_munged) %>% #site_413646087260101_munged can be used without spec_cond
    filter_all(all_vars(!is.na(.)))%>%
  
  mutate(water_year = if_else(month(dateTime) >= 10, year(dateTime) + 1, year(dateTime)),
         month=month(dateTime)) # %>% 
  #mutate_all(~ifelse(. < 0, 0, .))  # Replace negative numbers with zero

write.csv(munged_data,paste0(local_path,"Data/","munged_data.csv"),row.names = FALSE)
  


```
